#!/bin/bash

kill `cat /var/run/ers_daemon.pid`

DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PIDFILE="$DIR/couchdata/couch.pid"
if [ -f "$PIDFILE" ]
then
  kill -15 `cat "$PIDFILE"`
  rm "$PIDFILE"
else
  echo "CouchDB is not running or was started from an other directory."
fi

