#!/bin/bash
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PIDFILE="$DIR/couchdata/couch.pid"
if [ -f "$PIDFILE" ]
then
  kill -15 `cat "$PIDFILE"`
  rm "$PIDFILE"
else
  echo "CouchDB is not running or was started from an other directory."
fi
AP_PID="$DIR/couchdata/avahi-publish.pid"
if [ -f "$AP_PID" ]
then
  kill -15 `cat "$AP_PID"`
  rm "$AP_PID"
fi
